spring:
  profiles:
    active: prod  #指定当前使用的是生产环境配置
---
server:
  port: 8088
  servlet:
    context-path: /
spring:
  datasource:
    dricer-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/adweb_project?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
#springboot整合mybatis
mybatis:
  #  定义别名包
  type-aliases-package: com.study.backside.bean
  #    加载mapper映射文件
  mapper-locations: classpath:/mapper/*.xml
  #  开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
