spring:
  profiles:
    active: prod  #指定当前使用的是生产环境配置
---


# 自定义文件保存路径
gorit:
  file:
    root:
      path: http:\localhost\temp\
server:
  port: 8888
  servlet:
    context-path: /
spring:
  datasource:
    dricer-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ts?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2KB # 文件写入磁盘的阈值
      max-file-size: 100MB
      max-request-size: 215MB # 最大请求值大小

#springboot整合mybatis
mybatis:
  #  定义别名包
  type-aliases-package: com.study.backside.bean
  #    加载mapper映射文件
  mapper-locations: classpath:/mapper/*.xml
  #  开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
